# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=140)),
                ('tamano', models.CharField(choices=[('120', '120 m'), ('150', '150 m'), ('300', '300 m'), ('other', 'Otro')], default='Escoge un tamaño', max_length=5)),
                ('plazo', models.CharField(choices=[('1 año', '1 Año'), ('2 años', '2 Años'), ('3 años', '3 Años'), ('5 años', '5 Años')], default='Escoge un plazo', max_length=10)),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('hora', models.TimeField(auto_now=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-fecha', '-hora'),
            },
        ),
    ]
